version: "3"
services:
  jupyter:
    restart: always
    build: ./
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - "./data/jupyter:/home/jovyan/work"
      - "./config:/home/jovyan/.jupyter"
